/**
 * Some utility functions.
 */


/**
 * Module dependencies.
 */
var fs = require('fs');
var md = require('./markdown');

/**
 * Generated at information.
 */
exports.generateInfoMarkdown = function(version) {
  return '\n'+md.rule()+'\n\n'+
         '*This Readme was generated by '+md.link('http://www.github.com/subtub/subtool/releases/tag/v'+version, 'subtool')+' on '+Date()+'.*  \n';
}

/**
 * If package.json exists, load it.
 *
 * @param path - Path to the package.json filepath.
 */
exports.readPackageJson = function(path, callback) {
  fs.readFile(path, function(err, data) {
    if (err) {
      // if no package.json was found, return false
      callback(false);
    } else {
      var tmp = data.toString();
      var pkg = JSON.parse(tmp);
      callback(pkg);
    }
  });
}
